// <auto-generated />
using System;
using Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infra.Migrations
{
    [DbContext(typeof(ContextoAplicacao))]
    partial class ContextoAplicacaoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Anexo", b =>
                {
                    b.Property<long>("ProcessoId")
                        .HasColumnType("bigint");

                    b.Property<int>("FluxoProcessoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoProcessoId")
                        .HasColumnType("int");

                    b.Property<string>("AnexoId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Caminho")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("ImageBase64String")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeArquivo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TipoAnexo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ProcessoId", "FluxoProcessoId", "TipoProcessoId", "AnexoId");

                    b.HasIndex("TipoProcessoId");

                    b.HasIndex("FluxoProcessoId", "TipoProcessoId");

                    b.ToTable("Anexo", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Bairro", b =>
                {
                    b.Property<long>("BairroId")
                        .HasColumnType("bigint");

                    b.Property<int?>("CidadeId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<long?>("RegiaoId")
                        .HasColumnType("bigint");

                    b.HasKey("BairroId");

                    b.HasIndex("CidadeId");

                    b.HasIndex("RegiaoId");

                    b.ToTable("Bairro", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Cidade", b =>
                {
                    b.Property<int>("CidadeId")
                        .HasColumnType("int");

                    b.Property<int?>("DDDId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("EstadoId")
                        .HasColumnType("int");

                    b.Property<int?>("IDCidadeProsiga")
                        .HasColumnType("int");

                    b.Property<string>("UFProsiga")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int?>("ibge")
                        .HasColumnType("int");

                    b.Property<int?>("ibgeProsiga")
                        .HasColumnType("int");

                    b.HasKey("CidadeId");

                    b.HasIndex("DDDId");

                    b.HasIndex("EstadoId");

                    b.ToTable("Cidade", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Contato", b =>
                {
                    b.Property<int>("ContatoId")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<bool>("Principal")
                        .HasColumnType("bit");

                    b.Property<int?>("TipoContatoId")
                        .HasColumnType("int");

                    b.HasKey("ContatoId");

                    b.HasIndex("TipoContatoId");

                    b.ToTable("Contato", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entities.Contato_Pessoa", b =>
                {
                    b.Property<int>("ContatoId")
                        .HasColumnType("int");

                    b.Property<long>("PessoaId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("ContatoId", "PessoaId");

                    b.HasIndex("PessoaId");

                    b.ToTable("Contato_Pessoa", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DDD", b =>
                {
                    b.Property<int>("DDDId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoDDD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DDDId");

                    b.ToTable("DDD", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Divisao", b =>
                {
                    b.Property<int>("DivisaoId")
                        .HasColumnType("int");

                    b.Property<string>("Atribuicao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("LocalId")
                        .HasColumnType("int");

                    b.Property<long?>("ServidorResponsavelId")
                        .HasColumnType("bigint");

                    b.Property<int?>("UnidadeId")
                        .HasColumnType("int");

                    b.HasKey("DivisaoId");

                    b.HasIndex("LocalId");

                    b.HasIndex("ServidorResponsavelId");

                    b.HasIndex("UnidadeId");

                    b.ToTable("Divisao", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DocumentoPessoa", b =>
                {
                    b.Property<int>("DocumentoPessoaId")
                        .HasColumnType("int");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<long>("PessoaId")
                        .HasColumnType("bigint");

                    b.Property<int>("TipoDocumentoId")
                        .HasColumnType("int");

                    b.HasKey("DocumentoPessoaId");

                    b.HasIndex("PessoaId");

                    b.HasIndex("TipoDocumentoId");

                    b.ToTable("DocumentoPessoa", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entities.Economia", b =>
                {
                    b.Property<long>("ImovelId")
                        .HasColumnType("bigint");

                    b.Property<long>("EconomiaId")
                        .HasColumnType("bigint");

                    b.Property<string>("AnoConstrucao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AreaConstruida")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Caracteristica")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Complemento")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Latitude")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Longitude")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Matricula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numeracao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("TemProcessos")
                        .HasColumnType("bit");

                    b.Property<string>("TerrenoIdTemp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ImovelId", "EconomiaId");

                    b.ToTable("Economia", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Economia_Entidade", b =>
                {
                    b.Property<long?>("ImovelId")
                        .HasColumnType("bigint");

                    b.Property<long?>("EconomiaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PessoaId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("CoResponsavel")
                        .HasColumnType("bit");

                    b.Property<bool?>("Correspondente")
                        .HasColumnType("bit");

                    b.Property<bool?>("Locatario")
                        .HasColumnType("bit");

                    b.Property<bool?>("Proprietario")
                        .HasColumnType("bit");

                    b.Property<bool?>("Responsavel")
                        .HasColumnType("bit");

                    b.Property<int?>("TipoResponsabilidadeId")
                        .HasColumnType("int");

                    b.HasKey("ImovelId", "EconomiaId", "PessoaId");

                    b.HasIndex("PessoaId");

                    b.HasIndex("TipoResponsabilidadeId");

                    b.ToTable("Economia_Entidade", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Endereco", b =>
                {
                    b.Property<long>("EnderecoId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("Ativo")
                        .HasColumnType("bit");

                    b.Property<long?>("BairroId")
                        .HasColumnType("bigint");

                    b.Property<string>("CEP")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("CidadeId")
                        .HasColumnType("int");

                    b.Property<string>("Complemento")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("LogradouroId")
                        .HasColumnType("bigint");

                    b.Property<string>("Referencia")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("logradouro_Temp")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("EnderecoId");

                    b.HasIndex("BairroId");

                    b.HasIndex("CidadeId");

                    b.HasIndex("LogradouroId");

                    b.ToTable("Endereco", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Endereco_Entidade", b =>
                {
                    b.Property<long>("EntidadeId")
                        .HasColumnType("bigint");

                    b.Property<long>("EnderecoId")
                        .HasColumnType("bigint");

                    b.Property<int?>("TipoEntidadeId")
                        .HasColumnType("int");

                    b.Property<string>("Numero")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool?>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("CEP")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool?>("Correspondencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime?>("DataUltimaAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<long?>("EconomiaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ImovelId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PessoaId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("Principal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("EntidadeId", "EnderecoId", "TipoEntidadeId", "Numero");

                    b.HasIndex("EnderecoId");

                    b.HasIndex("PessoaId");

                    b.HasIndex("ImovelId", "EconomiaId");

                    b.ToTable("Endereco_Entidade", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Estado", b =>
                {
                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PaisId")
                        .HasColumnType("int");

                    b.Property<string>("Sigla")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("EstadoId");

                    b.HasIndex("PaisId");

                    b.ToTable("Estado", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Etapa", b =>
                {
                    b.Property<long>("ProcessoId")
                        .HasColumnType("bigint");

                    b.Property<int>("FluxoProcessoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoProcessoId")
                        .HasColumnType("int");

                    b.Property<string>("Ano")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("ObservacaoEtapa")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ServidorId")
                        .HasColumnType("bigint");

                    b.Property<int?>("SituacaoEtapaId")
                        .HasColumnType("int");

                    b.Property<string>("anoprotocolo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool?>("antigo")
                        .HasColumnType("bit");

                    b.Property<bool?>("emailEnviado")
                        .HasColumnType("bit");

                    b.Property<bool?>("emailRecebido")
                        .HasColumnType("bit");

                    b.Property<string>("protocolo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool?>("whatsEnviado")
                        .HasColumnType("bit");

                    b.Property<bool?>("whatsRecebido")
                        .HasColumnType("bit");

                    b.HasKey("ProcessoId", "FluxoProcessoId", "TipoProcessoId");

                    b.HasIndex("ServidorId");

                    b.HasIndex("SituacaoEtapaId");

                    b.HasIndex("TipoProcessoId");

                    b.HasIndex("FluxoProcessoId", "TipoProcessoId");

                    b.ToTable("Etapa", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.FluxoProcesso", b =>
                {
                    b.Property<int>("FluxoProcessoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoProcessoId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TempoTramitacao")
                        .HasColumnType("int");

                    b.HasKey("FluxoProcessoId", "TipoProcessoId");

                    b.HasIndex("TipoProcessoId");

                    b.ToTable("FluxoProcesso", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Imovel", b =>
                {
                    b.Property<long>("ImovelId")
                        .HasColumnType("bigint");

                    b.Property<string>("AnoConstrucao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AreaConstruida")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AreaTerreno")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Caracteristica")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Complemento")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Latitude")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Longitude")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Matricula")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ImovelId");

                    b.ToTable("Imovel", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.IncrementoTabelas", b =>
                {
                    b.Property<int>("IncrementoTabelasId")
                        .HasColumnType("int");

                    b.Property<string>("Ano")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Parametro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tabela")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("valorAtual")
                        .HasColumnType("bigint");

                    b.Property<long?>("valorFinal")
                        .HasColumnType("bigint");

                    b.Property<long?>("valorInicial")
                        .HasColumnType("bigint");

                    b.Property<int?>("valorincrementar")
                        .HasColumnType("int");

                    b.HasKey("IncrementoTabelasId");

                    b.ToTable("IncrementoTabelas", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Local", b =>
                {
                    b.Property<int>("LocalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocalId"));

                    b.HasKey("LocalId");

                    b.ToTable("Local", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Logradouro", b =>
                {
                    b.Property<long>("LogradouroId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("Ativo")
                        .HasColumnType("bit");

                    b.Property<long?>("BairroId")
                        .HasColumnType("bigint");

                    b.Property<string>("CEP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CidadeId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("TipoLogradouroId")
                        .HasColumnType("int");

                    b.Property<string>("descricaoTipoLogradouro")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("LogradouroId");

                    b.HasIndex("BairroId");

                    b.HasIndex("CidadeId");

                    b.HasIndex("TipoLogradouroId");

                    b.ToTable("Logradouro", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Loteamento", b =>
                {
                    b.Property<int>("LoteamentoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("RegiaoId")
                        .HasColumnType("bigint");

                    b.HasKey("LoteamentoId");

                    b.HasIndex("RegiaoId");

                    b.ToTable("Loteamento", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ObjetoProcesso", b =>
                {
                    b.Property<long>("ProcessoId")
                        .HasColumnType("bigint");

                    b.Property<string>("DescricaoObjetoProcesso")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Não Definido");

                    b.Property<long?>("EconomiaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("EnderecoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ImovelId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PessoaId")
                        .HasColumnType("bigint");

                    b.Property<int>("TipoObjetoProcesso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("ProcessoId");

                    b.HasIndex("EnderecoId");

                    b.HasIndex("PessoaId");

                    b.HasIndex("ImovelId", "EconomiaId");

                    b.ToTable("ObjetoProcesso", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.OperadoraTelefone", b =>
                {
                    b.Property<int>("OperadoraTelefoneId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoOperadora")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("OperadoraTelefoneId");

                    b.ToTable("OperadoraTelefone", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Orgao", b =>
                {
                    b.Property<int>("OrgaoId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("OrgaoId");

                    b.ToTable("Orgao", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Pais", b =>
                {
                    b.Property<int>("PaisId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("PaisId");

                    b.ToTable("Pais", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Perspectiva", b =>
                {
                    b.Property<int?>("PerspectivaId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PerspectivaId");

                    b.ToTable("Perspectiva", (string)null);

                    b.HasData(
                        new
                        {
                            PerspectivaId = 1,
                            Descricao = "Frontal"
                        },
                        new
                        {
                            PerspectivaId = 2,
                            Descricao = "Lateral Direita"
                        },
                        new
                        {
                            PerspectivaId = 3,
                            Descricao = "Lateral Esquerda"
                        },
                        new
                        {
                            PerspectivaId = 4,
                            Descricao = "Fundo"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Pessoa", b =>
                {
                    b.Property<long>("PessoaId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("TipoPessoaId")
                        .HasColumnType("int");

                    b.Property<long?>("conId")
                        .HasColumnType("bigint");

                    b.HasKey("PessoaId");

                    b.HasIndex("TipoPessoaId");

                    b.ToTable("Pessoa", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entities.Processo", b =>
                {
                    b.Property<long>("ProcessoId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Ano")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int?>("DivisaoDestinatarioId")
                        .HasColumnType("int");

                    b.Property<int?>("DivisaoId")
                        .HasColumnType("int");

                    b.Property<int?>("DivisaoRemetenteId")
                        .HasColumnType("int");

                    b.Property<string>("ObservacaoProcesso")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("OrgaoDestinatarioId")
                        .HasColumnType("int");

                    b.Property<int?>("OrgaoId")
                        .HasColumnType("int");

                    b.Property<int?>("OrgaoRemetenteId")
                        .HasColumnType("int");

                    b.Property<bool?>("ProcessoAntigo")
                        .HasColumnType("bit");

                    b.Property<bool?>("ProcessoEnviado")
                        .HasColumnType("bit");

                    b.Property<bool?>("ProcessoRecebido")
                        .HasColumnType("bit");

                    b.Property<long?>("ServidorId")
                        .HasColumnType("bigint");

                    b.Property<int?>("SituacaoProcessoId")
                        .HasColumnType("int");

                    b.Property<int?>("TipoProcessoId")
                        .HasColumnType("int");

                    b.Property<int?>("UnidadeDestinatarioId")
                        .HasColumnType("int");

                    b.Property<int?>("UnidadeId")
                        .HasColumnType("int");

                    b.Property<int?>("UnidadeRemetenteId")
                        .HasColumnType("int");

                    b.HasKey("ProcessoId");

                    b.HasIndex("DivisaoDestinatarioId");

                    b.HasIndex("DivisaoId");

                    b.HasIndex("DivisaoRemetenteId");

                    b.HasIndex("OrgaoDestinatarioId");

                    b.HasIndex("OrgaoId");

                    b.HasIndex("OrgaoRemetenteId");

                    b.HasIndex("ServidorId");

                    b.HasIndex("SituacaoProcessoId");

                    b.HasIndex("TipoProcessoId");

                    b.HasIndex("UnidadeDestinatarioId");

                    b.HasIndex("UnidadeId");

                    b.HasIndex("UnidadeRemetenteId");

                    b.ToTable("Processo", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Regiao", b =>
                {
                    b.Property<long>("RegiaoId")
                        .HasColumnType("bigint");

                    b.Property<string>("CentroGrauLat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CentroGrauLon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CidadeId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<float?>("PercentualUVC")
                        .HasColumnType("real");

                    b.HasKey("RegiaoId");

                    b.HasIndex("CidadeId");

                    b.ToTable("Regiao", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Servidor", b =>
                {
                    b.Property<long>("ServidorId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Cargo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("DivisaoId")
                        .HasColumnType("int");

                    b.Property<string>("Funcao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Matricula")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Nome")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("UnidadeId")
                        .HasColumnType("int");

                    b.HasKey("ServidorId");

                    b.HasIndex("DivisaoId");

                    b.HasIndex("UnidadeId");

                    b.ToTable("Servidor", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Servidor_TipoProcesso", b =>
                {
                    b.Property<long>("ServidorId")
                        .HasColumnType("bigint");

                    b.Property<int>("TipoProcessoId")
                        .HasColumnType("int");

                    b.HasKey("ServidorId", "TipoProcessoId");

                    b.HasIndex("TipoProcessoId");

                    b.ToTable("Servidor_TipoProcesso", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.SituacaoEtapa", b =>
                {
                    b.Property<int>("SituacaoEtapaId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SituacaoEtapaId");

                    b.ToTable("SituacaoEtapa", (string)null);

                    b.HasData(
                        new
                        {
                            SituacaoEtapaId = 1,
                            Descricao = "Iniciado"
                        },
                        new
                        {
                            SituacaoEtapaId = 2,
                            Descricao = "Finalizado"
                        },
                        new
                        {
                            SituacaoEtapaId = 3,
                            Descricao = "Trâmite"
                        });
                });

            modelBuilder.Entity("Domain.Entities.SituacaoProcesso", b =>
                {
                    b.Property<int>("SituacaoProcessoId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SituacaoProcessoId");

                    b.ToTable("SituacaoProcesso", (string)null);

                    b.HasData(
                        new
                        {
                            SituacaoProcessoId = 1,
                            Descricao = "Iniciado"
                        },
                        new
                        {
                            SituacaoProcessoId = 2,
                            Descricao = "Finalizado"
                        });
                });

            modelBuilder.Entity("Domain.Entities.TipoContato", b =>
                {
                    b.Property<int>("TipoContatoId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TipoContatoId");

                    b.ToTable("TipoContato", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.TipoDocumento", b =>
                {
                    b.Property<int>("TipoDocumentoId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("TipoDocumentoId");

                    b.ToTable("TipoDocumento", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.TipoEtapa", b =>
                {
                    b.Property<int>("TipoEtapaId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int?>("DiasTramite")
                        .HasColumnType("int");

                    b.Property<string>("Lei")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Permanencia")
                        .HasColumnType("int");

                    b.Property<string>("Template")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextoLei")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("liberado")
                        .HasColumnType("bit");

                    b.HasKey("TipoEtapaId");

                    b.ToTable("TipoEtapa", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.TipoLogradouro", b =>
                {
                    b.Property<int>("TipoLogradouroId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("TipoLogradouroId");

                    b.ToTable("TipoLogradouro", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.TipoPessoa", b =>
                {
                    b.Property<int>("TipoPessoaId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TipoPessoaId");

                    b.ToTable("TipoPessoa", (string)null);

                    b.HasData(
                        new
                        {
                            TipoPessoaId = 1,
                            Descricao = "FÍSICA"
                        },
                        new
                        {
                            TipoPessoaId = 2,
                            Descricao = "JURÍDICA"
                        });
                });

            modelBuilder.Entity("Domain.Entities.TipoProcesso", b =>
                {
                    b.Property<int>("TipoProcessoId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("DiasTramite")
                        .HasColumnType("int");

                    b.Property<int?>("Permanencia")
                        .HasColumnType("int");

                    b.Property<bool?>("liberado")
                        .HasColumnType("bit");

                    b.HasKey("TipoProcessoId");

                    b.ToTable("TipoProcesso", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.TipoResponsabilidade", b =>
                {
                    b.Property<int>("TipoResponsabilidadeId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TipoResponsabilidadeId");

                    b.ToTable("TipoResponsabilidade", (string)null);

                    b.HasData(
                        new
                        {
                            TipoResponsabilidadeId = 1,
                            Descricao = "Proprietário"
                        },
                        new
                        {
                            TipoResponsabilidadeId = 2,
                            Descricao = "Responsável"
                        },
                        new
                        {
                            TipoResponsabilidadeId = 3,
                            Descricao = "Co-Responsável"
                        });
                });

            modelBuilder.Entity("Domain.Entities.TipoTelefone", b =>
                {
                    b.Property<int>("TipoTelefoneId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("TipoTelefoneId");

                    b.ToTable("TipoTelefone", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Unidade", b =>
                {
                    b.Property<int>("UnidadeId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("OrgaoId")
                        .HasColumnType("int");

                    b.HasKey("UnidadeId");

                    b.HasIndex("OrgaoId");

                    b.ToTable("Unidade", (string)null);
                });

            modelBuilder.Entity("Infra.Context.ApplicationUser", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ServidorId")
                        .HasColumnType("bigint");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("ServidorId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<long>", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Telefone", b =>
                {
                    b.HasBaseType("Domain.Entities.Contato");

                    b.Property<int?>("DDDId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimaAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("OperadoraTelefoneId")
                        .HasColumnType("int");

                    b.Property<int>("TipoTelefoneId")
                        .HasColumnType("int");

                    b.HasIndex("DDDId");

                    b.HasIndex("OperadoraTelefoneId");

                    b.HasIndex("TipoTelefoneId");

                    b.ToTable("Telefone", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CNPJ", b =>
                {
                    b.HasBaseType("Domain.Entities.DocumentoPessoa");

                    b.Property<DateTime?>("DataExpedicao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EstadoEmissorId")
                        .HasColumnType("int");

                    b.Property<string>("OrgaoEmissor")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasIndex("EstadoEmissorId");

                    b.ToTable("CNPJ", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CPF", b =>
                {
                    b.HasBaseType("Domain.Entities.DocumentoPessoa");

                    b.Property<DateTime?>("DataExpedicao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EstadoEmissorId")
                        .HasColumnType("int");

                    b.Property<string>("OrgaoEmissor")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasIndex("EstadoEmissorId");

                    b.ToTable("CPF", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.RG", b =>
                {
                    b.HasBaseType("Domain.Entities.DocumentoPessoa");

                    b.Property<DateTime?>("DataExpedicao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EstadoEmissorId")
                        .HasColumnType("int");

                    b.Property<string>("OrgaoEmissor")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasIndex("EstadoEmissorId");

                    b.ToTable("RG", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.PessoaFisica", b =>
                {
                    b.HasBaseType("Domain.Entities.Pessoa");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataObito")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefinicaoSexual")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("EstadoCivil")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NomeMeio")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("PaisId")
                        .HasColumnType("int");

                    b.Property<string>("PrimeiroNome")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sexo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sobrenome")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasIndex("PaisId");

                    b.ToTable("PessoaFisica", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.PessoaJuridica", b =>
                {
                    b.HasBaseType("Domain.Entities.Pessoa");

                    b.Property<string>("InscricaoEstadual")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NomeFantasia")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RazaoSocial")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.ToTable("PessoaJuridica", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Anexo", b =>
                {
                    b.HasOne("Domain.Entities.Processo", "Processo")
                        .WithMany()
                        .HasForeignKey("ProcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TipoProcesso", "TipoProcesso")
                        .WithMany()
                        .HasForeignKey("TipoProcessoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.FluxoProcesso", "FluxoProcesso")
                        .WithMany()
                        .HasForeignKey("FluxoProcessoId", "TipoProcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Etapa", "Etapa")
                        .WithMany("Anexos")
                        .HasForeignKey("ProcessoId", "FluxoProcessoId", "TipoProcessoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Etapa");

                    b.Navigation("FluxoProcesso");

                    b.Navigation("Processo");

                    b.Navigation("TipoProcesso");
                });

            modelBuilder.Entity("Domain.Entities.Bairro", b =>
                {
                    b.HasOne("Domain.Entities.Cidade", "Cidade")
                        .WithMany("Bairros")
                        .HasForeignKey("CidadeId");

                    b.HasOne("Domain.Entities.Regiao", "Regiao")
                        .WithMany()
                        .HasForeignKey("RegiaoId");

                    b.Navigation("Cidade");

                    b.Navigation("Regiao");
                });

            modelBuilder.Entity("Domain.Entities.Cidade", b =>
                {
                    b.HasOne("Domain.Entities.DDD", "DDD")
                        .WithMany()
                        .HasForeignKey("DDDId");

                    b.HasOne("Domain.Entities.Estado", "Estado")
                        .WithMany("Cidades")
                        .HasForeignKey("EstadoId");

                    b.Navigation("DDD");

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("Domain.Entities.Contato", b =>
                {
                    b.HasOne("Domain.Entities.TipoContato", "TipoContato")
                        .WithMany()
                        .HasForeignKey("TipoContatoId");

                    b.Navigation("TipoContato");
                });

            modelBuilder.Entity("Domain.Entities.Contato_Pessoa", b =>
                {
                    b.HasOne("Domain.Entities.Contato", "Contato")
                        .WithMany("Pessoas")
                        .HasForeignKey("ContatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Pessoa", "Pessoa")
                        .WithMany("Contatos")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contato");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Domain.Entities.Divisao", b =>
                {
                    b.HasOne("Domain.Entities.Local", "Local")
                        .WithMany()
                        .HasForeignKey("LocalId");

                    b.HasOne("Domain.Entities.Servidor", "ServidorResponsavel")
                        .WithMany()
                        .HasForeignKey("ServidorResponsavelId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Entities.Unidade", "Unidade")
                        .WithMany("Divisoes")
                        .HasForeignKey("UnidadeId");

                    b.Navigation("Local");

                    b.Navigation("ServidorResponsavel");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("Domain.Entities.DocumentoPessoa", b =>
                {
                    b.HasOne("Domain.Entities.Pessoa", "Pessoa")
                        .WithMany("Documentos")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TipoDocumento", "TipoDocumento")
                        .WithMany()
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("Domain.Entities.Economia", b =>
                {
                    b.HasOne("Domain.Entities.Imovel", "Imovel")
                        .WithMany()
                        .HasForeignKey("ImovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Imovel");
                });

            modelBuilder.Entity("Domain.Entities.Economia_Entidade", b =>
                {
                    b.HasOne("Domain.Entities.Imovel", "Imovel")
                        .WithMany("Economias")
                        .HasForeignKey("ImovelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Pessoa", "Pessoa")
                        .WithMany("Economias")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TipoResponsabilidade", "TipoResponsabilidade")
                        .WithMany()
                        .HasForeignKey("TipoResponsabilidadeId");

                    b.HasOne("Domain.Entities.Economia", "Economia")
                        .WithMany("Pessoas")
                        .HasForeignKey("ImovelId", "EconomiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Economia");

                    b.Navigation("Imovel");

                    b.Navigation("Pessoa");

                    b.Navigation("TipoResponsabilidade");
                });

            modelBuilder.Entity("Domain.Entities.Endereco", b =>
                {
                    b.HasOne("Domain.Entities.Bairro", "Bairro")
                        .WithMany()
                        .HasForeignKey("BairroId");

                    b.HasOne("Domain.Entities.Cidade", "Cidade")
                        .WithMany()
                        .HasForeignKey("CidadeId");

                    b.HasOne("Domain.Entities.Logradouro", "Logradouro")
                        .WithMany("Enderecos")
                        .HasForeignKey("LogradouroId");

                    b.Navigation("Bairro");

                    b.Navigation("Cidade");

                    b.Navigation("Logradouro");
                });

            modelBuilder.Entity("Domain.Entities.Endereco_Entidade", b =>
                {
                    b.HasOne("Domain.Entities.Endereco", "Endereco")
                        .WithMany("Entidades")
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Imovel", "Imovel")
                        .WithMany("Enderecos")
                        .HasForeignKey("ImovelId");

                    b.HasOne("Domain.Entities.Pessoa", "Pessoa")
                        .WithMany("Enderecos")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Entities.Economia", "Economia")
                        .WithMany("Enderecos")
                        .HasForeignKey("ImovelId", "EconomiaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Economia");

                    b.Navigation("Endereco");

                    b.Navigation("Imovel");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Domain.Entities.Estado", b =>
                {
                    b.HasOne("Domain.Entities.Pais", "Pais")
                        .WithMany("Estados")
                        .HasForeignKey("PaisId");

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("Domain.Entities.Etapa", b =>
                {
                    b.HasOne("Domain.Entities.Processo", "Processo")
                        .WithMany("Etapas")
                        .HasForeignKey("ProcessoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Servidor", "Servidor")
                        .WithMany()
                        .HasForeignKey("ServidorId");

                    b.HasOne("Domain.Entities.SituacaoEtapa", "SituacaoEtapa")
                        .WithMany()
                        .HasForeignKey("SituacaoEtapaId");

                    b.HasOne("Domain.Entities.TipoProcesso", "TipoProcesso")
                        .WithMany("Etapas")
                        .HasForeignKey("TipoProcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.FluxoProcesso", "FluxoProcesso")
                        .WithMany("Etapas")
                        .HasForeignKey("FluxoProcessoId", "TipoProcessoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FluxoProcesso");

                    b.Navigation("Processo");

                    b.Navigation("Servidor");

                    b.Navigation("SituacaoEtapa");

                    b.Navigation("TipoProcesso");
                });

            modelBuilder.Entity("Domain.Entities.FluxoProcesso", b =>
                {
                    b.HasOne("Domain.Entities.TipoProcesso", "TipoProcesso")
                        .WithMany("FluxoProcessos")
                        .HasForeignKey("TipoProcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoProcesso");
                });

            modelBuilder.Entity("Domain.Entities.Logradouro", b =>
                {
                    b.HasOne("Domain.Entities.Bairro", "Bairro")
                        .WithMany()
                        .HasForeignKey("BairroId");

                    b.HasOne("Domain.Entities.Cidade", "Cidade")
                        .WithMany("Logradouros")
                        .HasForeignKey("CidadeId");

                    b.HasOne("Domain.Entities.TipoLogradouro", "TipoLogradouro")
                        .WithMany()
                        .HasForeignKey("TipoLogradouroId");

                    b.Navigation("Bairro");

                    b.Navigation("Cidade");

                    b.Navigation("TipoLogradouro");
                });

            modelBuilder.Entity("Domain.Entities.Loteamento", b =>
                {
                    b.HasOne("Domain.Entities.Regiao", "Regiao")
                        .WithMany()
                        .HasForeignKey("RegiaoId");

                    b.Navigation("Regiao");
                });

            modelBuilder.Entity("Domain.Entities.ObjetoProcesso", b =>
                {
                    b.HasOne("Domain.Entities.Endereco", "Endereco")
                        .WithMany("ObjetoProcessos")
                        .HasForeignKey("EnderecoId");

                    b.HasOne("Domain.Entities.Imovel", "Imovel")
                        .WithMany("ObjetoProcessos")
                        .HasForeignKey("ImovelId");

                    b.HasOne("Domain.Entities.Pessoa", "Pessoa")
                        .WithMany("ObjetoProcessos")
                        .HasForeignKey("PessoaId");

                    b.HasOne("Domain.Entities.Processo", "Processo")
                        .WithOne("ObjetoProcesso")
                        .HasForeignKey("Domain.Entities.ObjetoProcesso", "ProcessoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Economia", "Economia")
                        .WithMany("ObjetoProcessos")
                        .HasForeignKey("ImovelId", "EconomiaId");

                    b.Navigation("Economia");

                    b.Navigation("Endereco");

                    b.Navigation("Imovel");

                    b.Navigation("Pessoa");

                    b.Navigation("Processo");
                });

            modelBuilder.Entity("Domain.Entities.Pessoa", b =>
                {
                    b.HasOne("Domain.Entities.TipoPessoa", "TipoPessoa")
                        .WithMany()
                        .HasForeignKey("TipoPessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoPessoa");
                });

            modelBuilder.Entity("Domain.Entities.Processo", b =>
                {
                    b.HasOne("Domain.Entities.Divisao", "DivisaoDestinatario")
                        .WithMany()
                        .HasForeignKey("DivisaoDestinatarioId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Entities.Divisao", "Divisao")
                        .WithMany("Processos")
                        .HasForeignKey("DivisaoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Entities.Divisao", "DivisaoRemetente")
                        .WithMany()
                        .HasForeignKey("DivisaoRemetenteId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Entities.Orgao", "OrgaoDestinatario")
                        .WithMany()
                        .HasForeignKey("OrgaoDestinatarioId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Entities.Orgao", "Orgao")
                        .WithMany()
                        .HasForeignKey("OrgaoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Entities.Orgao", "OrgaoRemetente")
                        .WithMany()
                        .HasForeignKey("OrgaoRemetenteId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Entities.Servidor", "Servidor")
                        .WithMany("Processos")
                        .HasForeignKey("ServidorId");

                    b.HasOne("Domain.Entities.SituacaoProcesso", "SituacaoProcesso")
                        .WithMany()
                        .HasForeignKey("SituacaoProcessoId");

                    b.HasOne("Domain.Entities.TipoProcesso", "TipoProcesso")
                        .WithMany()
                        .HasForeignKey("TipoProcessoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Entities.Unidade", "UnidadeDestinatario")
                        .WithMany()
                        .HasForeignKey("UnidadeDestinatarioId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Entities.Unidade", "Unidade")
                        .WithMany("Processos")
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Entities.Unidade", "UnidadeRemetente")
                        .WithMany()
                        .HasForeignKey("UnidadeRemetenteId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Divisao");

                    b.Navigation("DivisaoDestinatario");

                    b.Navigation("DivisaoRemetente");

                    b.Navigation("Orgao");

                    b.Navigation("OrgaoDestinatario");

                    b.Navigation("OrgaoRemetente");

                    b.Navigation("Servidor");

                    b.Navigation("SituacaoProcesso");

                    b.Navigation("TipoProcesso");

                    b.Navigation("Unidade");

                    b.Navigation("UnidadeDestinatario");

                    b.Navigation("UnidadeRemetente");
                });

            modelBuilder.Entity("Domain.Entities.Regiao", b =>
                {
                    b.HasOne("Domain.Entities.Cidade", "Cidade")
                        .WithMany()
                        .HasForeignKey("CidadeId");

                    b.Navigation("Cidade");
                });

            modelBuilder.Entity("Domain.Entities.Servidor", b =>
                {
                    b.HasOne("Domain.Entities.Divisao", "Divisao")
                        .WithMany("Servidores")
                        .HasForeignKey("DivisaoId");

                    b.HasOne("Domain.Entities.Unidade", "Unidade")
                        .WithMany()
                        .HasForeignKey("UnidadeId");

                    b.Navigation("Divisao");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("Domain.Entities.Servidor_TipoProcesso", b =>
                {
                    b.HasOne("Domain.Entities.Servidor", "Servidor")
                        .WithMany("PodeExecutar")
                        .HasForeignKey("ServidorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TipoProcesso", "TipoProcesso")
                        .WithMany("ExecutadoPor")
                        .HasForeignKey("TipoProcessoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Servidor");

                    b.Navigation("TipoProcesso");
                });

            modelBuilder.Entity("Domain.Entities.Unidade", b =>
                {
                    b.HasOne("Domain.Entities.Orgao", "Orgao")
                        .WithMany("Unidades")
                        .HasForeignKey("OrgaoId");

                    b.Navigation("Orgao");
                });

            modelBuilder.Entity("Infra.Context.ApplicationUser", b =>
                {
                    b.HasOne("Domain.Entities.Servidor", "Servidor")
                        .WithMany()
                        .HasForeignKey("ServidorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Servidor");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<long>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("Infra.Context.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("Infra.Context.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<long>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infra.Context.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("Infra.Context.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Telefone", b =>
                {
                    b.HasOne("Domain.Entities.Contato", null)
                        .WithOne()
                        .HasForeignKey("Domain.Entities.Telefone", "ContatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.DDD", "DDD")
                        .WithMany()
                        .HasForeignKey("DDDId");

                    b.HasOne("Domain.Entities.OperadoraTelefone", "OperadoraTelefone")
                        .WithMany()
                        .HasForeignKey("OperadoraTelefoneId");

                    b.HasOne("Domain.Entities.TipoTelefone", "TipoTelefone")
                        .WithMany()
                        .HasForeignKey("TipoTelefoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DDD");

                    b.Navigation("OperadoraTelefone");

                    b.Navigation("TipoTelefone");
                });

            modelBuilder.Entity("Domain.Entities.CNPJ", b =>
                {
                    b.HasOne("Domain.Entities.DocumentoPessoa", null)
                        .WithOne()
                        .HasForeignKey("Domain.Entities.CNPJ", "DocumentoPessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Estado", "EstadoEmissor")
                        .WithMany()
                        .HasForeignKey("EstadoEmissorId");

                    b.Navigation("EstadoEmissor");
                });

            modelBuilder.Entity("Domain.Entities.CPF", b =>
                {
                    b.HasOne("Domain.Entities.DocumentoPessoa", null)
                        .WithOne()
                        .HasForeignKey("Domain.Entities.CPF", "DocumentoPessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Estado", "EstadoEmissor")
                        .WithMany()
                        .HasForeignKey("EstadoEmissorId");

                    b.Navigation("EstadoEmissor");
                });

            modelBuilder.Entity("Domain.Entities.RG", b =>
                {
                    b.HasOne("Domain.Entities.DocumentoPessoa", null)
                        .WithOne()
                        .HasForeignKey("Domain.Entities.RG", "DocumentoPessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Estado", "EstadoEmissor")
                        .WithMany()
                        .HasForeignKey("EstadoEmissorId");

                    b.Navigation("EstadoEmissor");
                });

            modelBuilder.Entity("Domain.Entities.PessoaFisica", b =>
                {
                    b.HasOne("Domain.Entities.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId");

                    b.HasOne("Domain.Entities.Pessoa", null)
                        .WithOne()
                        .HasForeignKey("Domain.Entities.PessoaFisica", "PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("Domain.Entities.PessoaJuridica", b =>
                {
                    b.HasOne("Domain.Entities.Pessoa", null)
                        .WithOne()
                        .HasForeignKey("Domain.Entities.PessoaJuridica", "PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Cidade", b =>
                {
                    b.Navigation("Bairros");

                    b.Navigation("Logradouros");
                });

            modelBuilder.Entity("Domain.Entities.Contato", b =>
                {
                    b.Navigation("Pessoas");
                });

            modelBuilder.Entity("Domain.Entities.Divisao", b =>
                {
                    b.Navigation("Processos");

                    b.Navigation("Servidores");
                });

            modelBuilder.Entity("Domain.Entities.Economia", b =>
                {
                    b.Navigation("Enderecos");

                    b.Navigation("ObjetoProcessos");

                    b.Navigation("Pessoas");
                });

            modelBuilder.Entity("Domain.Entities.Endereco", b =>
                {
                    b.Navigation("Entidades");

                    b.Navigation("ObjetoProcessos");
                });

            modelBuilder.Entity("Domain.Entities.Estado", b =>
                {
                    b.Navigation("Cidades");
                });

            modelBuilder.Entity("Domain.Entities.Etapa", b =>
                {
                    b.Navigation("Anexos");
                });

            modelBuilder.Entity("Domain.Entities.FluxoProcesso", b =>
                {
                    b.Navigation("Etapas");
                });

            modelBuilder.Entity("Domain.Entities.Imovel", b =>
                {
                    b.Navigation("Economias");

                    b.Navigation("Enderecos");

                    b.Navigation("ObjetoProcessos");
                });

            modelBuilder.Entity("Domain.Entities.Logradouro", b =>
                {
                    b.Navigation("Enderecos");
                });

            modelBuilder.Entity("Domain.Entities.Orgao", b =>
                {
                    b.Navigation("Unidades");
                });

            modelBuilder.Entity("Domain.Entities.Pais", b =>
                {
                    b.Navigation("Estados");
                });

            modelBuilder.Entity("Domain.Entities.Pessoa", b =>
                {
                    b.Navigation("Contatos");

                    b.Navigation("Documentos");

                    b.Navigation("Economias");

                    b.Navigation("Enderecos");

                    b.Navigation("ObjetoProcessos");
                });

            modelBuilder.Entity("Domain.Entities.Processo", b =>
                {
                    b.Navigation("Etapas");

                    b.Navigation("ObjetoProcesso");
                });

            modelBuilder.Entity("Domain.Entities.Servidor", b =>
                {
                    b.Navigation("PodeExecutar");

                    b.Navigation("Processos");
                });

            modelBuilder.Entity("Domain.Entities.TipoProcesso", b =>
                {
                    b.Navigation("Etapas");

                    b.Navigation("ExecutadoPor");

                    b.Navigation("FluxoProcessos");
                });

            modelBuilder.Entity("Domain.Entities.Unidade", b =>
                {
                    b.Navigation("Divisoes");

                    b.Navigation("Processos");
                });
#pragma warning restore 612, 618
        }
    }
}
