use NFSEDB
select --top(10)
	CO.STCPFCNPJ , 
	YEAR(DTCOMPETENCIA) AS ANO, 
	MONTH(DTCOMPETENCIA) AS MES,
	NF.NUNUMERO AS NUMERO, 
	2 as SITUACAO, 
	CASE WHEN IDOPERACAO = 1 THEN 1 ELSE 2 END as LOCALTRIBUTACAO,
    dbo.Formata(RTRIM(REPLACE(IDSERVICO,'.','')),'0000') as SERVICO116, 
	CASE WHEN STISSRETIDO = 'S' THEN 1 ELSE 0 END AS ISSRETIDO,
    REPLACE(CAST(VLBASECALCULO AS VARCHAR(40)),'.',',') AS BASECALCULO,
    REPLACE(PCALIQUOTA, '.', ',') AS ALIQUOTA,
	REPLACE(CASE WHEN STISSRETIDO = 'N' THEN VLTOTALISS ELSE 0 END,'.',',') AS VLRISS,
	REPLACE(CASE WHEN STISSRETIDO = 'S' THEN VLISSRETIDO ELSE 0 END, '.',',') AS VLRISSRETIDO,
	STPRE_IM as CMEPRESTADOR,
	CASE WHEN STTOM_PESSOA_TIPO = 'J' THEN dbo.formata(STTOM_CPFCNPJ,'00000000000000') ELSE dbo.formata(STTOM_CPFCNPJ,'00000000000') END AS CPFCNPJTOMADOR,
	REPLACE(STTOM_NOME, ';',' ') AS NOMETOMADOR,
	7563 AS TOM,
	CASE	WHEN IDOPERACAO = 1 THEN 1 
			WHEN IDOPERACAO = 2 THEN 1
			WHEN IDOPERACAO = 5 THEN 2
			WHEN IDOPERACAO = 3 THEN 3
			WHEN IDOPERACAO = 4 THEN 5
			WHEN IDOPERACAO = 6 THEN 6
			WHEN IDOPERACAO = 7 THEN 7
			ELSE 1 END 	AS EXIGIBILIDADE,
	REPLACE(VLDEDUCOES,'.',',') AS DEDUCOES,
	REPLACE(VLSERVICOS,'.',',') AS VLRSERVICO,
	STCODIGO AS CDVERIFICACAO
from NFSE_TBL_NFSE NF
	INNER JOIN NFSE_TBL_EMPRESA EM ON NF.IDEMPRESA = EM.IDEMPRESA
	INNER JOIN NFSE_TBL_CONTRIBUINTE CO ON EM.IDCONTRIBUINTE = CO.IDCONTRIBUINTE
WHERE DTDATA >= '01/01/2024'   AND  DTDATA <= '31/01/2024' AND NF.STSITUACAO = 'C'
--NUNUMERO=20232 and STPRE_CPFCNPJ=30651969000193
Order By Numero
